### ISSUE TITLE
Delete Function Not working

### ISSUE THREAD

**Issue by catcosmicice** [EvilVir/Nginx-Autoindex#1]
Hello,

I've just setup your cool autoindex on my web server, but it seems like delete doesn't work, I've tried uploading, and that works.
Not sure why delete doesn't work but if you can fix it soon, it'd be great.

Thanks,
[cosmicice](https://github.com/cosmicicedev)

**Comment by leojonathanoh** [comment]
i think i managed to find a fix, let me open an MR.
