### ISSUE TITLE
Navigation bar failing with spaces or unicode chars in directory names

### ISSUE THREAD

**Issue by BobbyWibowo** [EvilVir/Nginx-Autoindex#6]
![image](https://user-images.githubusercontent.com/9364930/167292161-0075b1dd-2027-4e27-919f-44e06b592d96.png)
![image](https://user-images.githubusercontent.com/9364930/167292179-14283aa0-1bd3-4f21-9f0a-cbfde41118d9.png)

Charset is properly set to utf-8
Clicking on the entries in the navigation bar will also fail because the href link is exact to what is shown as text

**Comment by BobbyWibowo** [comment]
Quick fix is to put `path[i]` through `decodeURI()` in
https://github.com/EvilVir/Nginx-Autoindex/blob/f500f2bcd41d3561da22360fcc86b66ee5e8a98f/autoindex.xslt#L40-L44
Also replacing what's referenced by `pathSoFar`, otherwise the link would still be unusable

**Comment by EvilVir** [comment]
Took me a while but should be fixed now. Thanks!
